name: ci

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v1
      with:
        python-version: "3.x"
    - uses: actions/checkout@v1
    - name: Lint with flake8
      run: |
        pip install --upgrade pip
        pip install flake8
        flake8 .
    - name: Lint with black
      run: |
        pip install black
        black --check .

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v1
      with:
        python-version: "3.x"
    - uses: actions/checkout@v1
      with:
        lfs: true
    - name: Install dependencies
      run: |
        sudo apt-get install -y libeigen3-dev python3-pip clang
    - name: install cgal-5 from ppa
      run: |
        sudo apt-get install -y software-properties-common
        sudo apt-add-repository -y ppa:nschloe/cgal-backports
        sudo apt update
        sudo apt install -y libcgal-dev
    - name: Install package
      run: |
        pip install --upgrade pip
        CC="clang" pip install .[all]
        pip install pytest pytest-cov
    - name: Test with pytest
      run: |
        cd test && pytest --cov pygalmesh
    # - name: Submit to codecov
    #   run: bash <(curl -s https://codecov.io/bash)
